# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from voice.client._generated import bots_pb2 as bots__pb2
from voice.client._generated import common_pb2 as common__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in bots_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BotsApiStub:
    """Self-service API: вызывается самим ботом по bot-токену (см. BotToken auth scheme в
    Vc.Backend.WebApi.Bots/Authentication), а не его владельцем. Для владельческого управления
    ботами (Keycloak JWT) см. user_bots.proto / UsersBots. Каждый метод (кроме GetMe) требует
    соответствующий scope — см. Vc.Common.Helpers.BotScopes и common.Bot.scopes.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMe = channel.unary_unary(
                '/bots.BotsApi/GetMe',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=common__pb2.Bot.FromString,
                _registered_method=True)
        self.SetStatus = channel.unary_unary(
                '/bots.BotsApi/SetStatus',
                request_serializer=bots__pb2.SetStatusRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.JoinVoiceChannel = channel.unary_unary(
                '/bots.BotsApi/JoinVoiceChannel',
                request_serializer=bots__pb2.JoinVoiceChannelRequest.SerializeToString,
                response_deserializer=bots__pb2.JoinVoiceChannelResponse.FromString,
                _registered_method=True)
        self.LeaveVoiceChannel = channel.unary_unary(
                '/bots.BotsApi/LeaveVoiceChannel',
                request_serializer=bots__pb2.LeaveVoiceChannelRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.SendMessage = channel.unary_unary(
                '/bots.BotsApi/SendMessage',
                request_serializer=bots__pb2.SendMessageRequest.SerializeToString,
                response_deserializer=bots__pb2.MessageInfo.FromString,
                _registered_method=True)
        self.UpdateMessage = channel.unary_unary(
                '/bots.BotsApi/UpdateMessage',
                request_serializer=bots__pb2.UpdateMessageRequest.SerializeToString,
                response_deserializer=bots__pb2.MessageInfo.FromString,
                _registered_method=True)
        self.DeleteMessage = channel.unary_unary(
                '/bots.BotsApi/DeleteMessage',
                request_serializer=bots__pb2.DeleteMessageRequest.SerializeToString,
                response_deserializer=bots__pb2.DeleteMessageResponse.FromString,
                _registered_method=True)
        self.AddReaction = channel.unary_unary(
                '/bots.BotsApi/AddReaction',
                request_serializer=bots__pb2.ReactionRequest.SerializeToString,
                response_deserializer=bots__pb2.MessageInfo.FromString,
                _registered_method=True)
        self.RemoveReaction = channel.unary_unary(
                '/bots.BotsApi/RemoveReaction',
                request_serializer=bots__pb2.ReactionRequest.SerializeToString,
                response_deserializer=bots__pb2.MessageInfo.FromString,
                _registered_method=True)
        self.GetChannelMessages = channel.unary_unary(
                '/bots.BotsApi/GetChannelMessages',
                request_serializer=bots__pb2.GetChannelMessagesRequest.SerializeToString,
                response_deserializer=bots__pb2.GetChannelMessagesResponse.FromString,
                _registered_method=True)
        self.GetMessage = channel.unary_unary(
                '/bots.BotsApi/GetMessage',
                request_serializer=bots__pb2.GetMessageRequest.SerializeToString,
                response_deserializer=bots__pb2.MessageInfo.FromString,
                _registered_method=True)
        self.Typing = channel.unary_unary(
                '/bots.BotsApi/Typing',
                request_serializer=bots__pb2.TypingRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.SetTyping = channel.unary_unary(
                '/bots.BotsApi/SetTyping',
                request_serializer=bots__pb2.BotTypingRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetMyGroups = channel.unary_unary(
                '/bots.BotsApi/GetMyGroups',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=bots__pb2.GetMyGroupsResponse.FromString,
                _registered_method=True)
        self.GetGroup = channel.unary_unary(
                '/bots.BotsApi/GetGroup',
                request_serializer=bots__pb2.GetGroupRequest.SerializeToString,
                response_deserializer=bots__pb2.BotGroupDetails.FromString,
                _registered_method=True)
        self.GetGroupCategories = channel.unary_unary(
                '/bots.BotsApi/GetGroupCategories',
                request_serializer=bots__pb2.GetGroupRequest.SerializeToString,
                response_deserializer=bots__pb2.GetGroupCategoriesResponse.FromString,
                _registered_method=True)
        self.GetGroupChannels = channel.unary_unary(
                '/bots.BotsApi/GetGroupChannels',
                request_serializer=bots__pb2.GetGroupRequest.SerializeToString,
                response_deserializer=bots__pb2.GetGroupChannelsResponse.FromString,
                _registered_method=True)
        self.GetGroupUsers = channel.unary_unary(
                '/bots.BotsApi/GetGroupUsers',
                request_serializer=bots__pb2.GetGroupUsersRequest.SerializeToString,
                response_deserializer=bots__pb2.GetGroupUsersResponse.FromString,
                _registered_method=True)
        self.GetUser = channel.unary_unary(
                '/bots.BotsApi/GetUser',
                request_serializer=bots__pb2.GetUserRequest.SerializeToString,
                response_deserializer=common__pb2.User.FromString,
                _registered_method=True)
        self.KickUser = channel.unary_unary(
                '/bots.BotsApi/KickUser',
                request_serializer=bots__pb2.KickUserRequest.SerializeToString,
                response_deserializer=bots__pb2.KickUserResponse.FromString,
                _registered_method=True)
        self.GetGroupRoles = channel.unary_unary(
                '/bots.BotsApi/GetGroupRoles',
                request_serializer=bots__pb2.GetGroupRolesRequest.SerializeToString,
                response_deserializer=bots__pb2.GetGroupRolesResponse.FromString,
                _registered_method=True)
        self.GetChannel = channel.unary_unary(
                '/bots.BotsApi/GetChannel',
                request_serializer=bots__pb2.GetChannelRequest.SerializeToString,
                response_deserializer=bots__pb2.BotChannelDetails.FromString,
                _registered_method=True)
        self.RespondToInteraction = channel.unary_unary(
                '/bots.BotsApi/RespondToInteraction',
                request_serializer=bots__pb2.RespondToInteractionRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.SendInteractionFollowup = channel.unary_unary(
                '/bots.BotsApi/SendInteractionFollowup',
                request_serializer=bots__pb2.SendInteractionFollowupRequest.SerializeToString,
                response_deserializer=bots__pb2.MessageInfo.FromString,
                _registered_method=True)
        self.CreateCategory = channel.unary_unary(
                '/bots.BotsApi/CreateCategory',
                request_serializer=bots__pb2.CreateCategoryRequest.SerializeToString,
                response_deserializer=bots__pb2.BotCategoryInfo.FromString,
                _registered_method=True)
        self.CreateChannel = channel.unary_unary(
                '/bots.BotsApi/CreateChannel',
                request_serializer=bots__pb2.CreateChannelRequest.SerializeToString,
                response_deserializer=bots__pb2.BotChannelInfo.FromString,
                _registered_method=True)
        self.GetCategory = channel.unary_unary(
                '/bots.BotsApi/GetCategory',
                request_serializer=bots__pb2.GetCategoryRequest.SerializeToString,
                response_deserializer=bots__pb2.BotCategoryInfo.FromString,
                _registered_method=True)
        self.UpdateChannel = channel.unary_unary(
                '/bots.BotsApi/UpdateChannel',
                request_serializer=bots__pb2.UpdateChannelRequest.SerializeToString,
                response_deserializer=bots__pb2.BotChannelInfo.FromString,
                _registered_method=True)
        self.UpdateCategory = channel.unary_unary(
                '/bots.BotsApi/UpdateCategory',
                request_serializer=bots__pb2.UpdateCategoryRequest.SerializeToString,
                response_deserializer=bots__pb2.BotCategoryInfo.FromString,
                _registered_method=True)
        self.DeleteChannel = channel.unary_unary(
                '/bots.BotsApi/DeleteChannel',
                request_serializer=bots__pb2.DeleteChannelRequest.SerializeToString,
                response_deserializer=bots__pb2.DeleteChannelResponse.FromString,
                _registered_method=True)
        self.DeleteCategory = channel.unary_unary(
                '/bots.BotsApi/DeleteCategory',
                request_serializer=bots__pb2.DeleteCategoryRequest.SerializeToString,
                response_deserializer=bots__pb2.DeleteCategoryResponse.FromString,
                _registered_method=True)
        self.CreateRole = channel.unary_unary(
                '/bots.BotsApi/CreateRole',
                request_serializer=bots__pb2.CreateRoleRequest.SerializeToString,
                response_deserializer=bots__pb2.BotRole.FromString,
                _registered_method=True)
        self.UpdateRole = channel.unary_unary(
                '/bots.BotsApi/UpdateRole',
                request_serializer=bots__pb2.UpdateRoleRequest.SerializeToString,
                response_deserializer=bots__pb2.BotRole.FromString,
                _registered_method=True)
        self.DeleteRole = channel.unary_unary(
                '/bots.BotsApi/DeleteRole',
                request_serializer=bots__pb2.DeleteRoleRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.AssignRole = channel.unary_unary(
                '/bots.BotsApi/AssignRole',
                request_serializer=bots__pb2.RoleAssignmentRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.RemoveRole = channel.unary_unary(
                '/bots.BotsApi/RemoveRole',
                request_serializer=bots__pb2.RoleAssignmentRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class BotsApiServicer:
    """Self-service API: вызывается самим ботом по bot-токену (см. BotToken auth scheme в
    Vc.Backend.WebApi.Bots/Authentication), а не его владельцем. Для владельческого управления
    ботами (Keycloak JWT) см. user_bots.proto / UsersBots. Каждый метод (кроме GetMe) требует
    соответствующий scope — см. Vc.Common.Helpers.BotScopes и common.Bot.scopes.
    """

    def GetMe(self, request, context):
        """Возвращает собственный профиль бота, аутентифицированного по bot-токену. Не требует intent —
        идентификация себя не является "действием".
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetStatus(self, request, context):
        """Устанавливает собственный presence-статус бота (ONLINE/OFFLINE/DO_NOT_DISTURB/INVISIBLE) — тот же
        UpdateUserStatusCommand, что и у человека (Users.UpdateUserStatus), просто вызванный от лица бота.
        Не требует intent, как и GetMe — это тоже действие над собой, а не над чужим пространством.
        Изменение статуса вживую (Discord-style) уходит всем участникам групп бота через group-events
        (см. Vc.Backend.WebApi.Users/Actors/UserActor.cs, BroadcastStatusChangeAsync).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JoinVoiceChannel(self, request, context):
        """Требует scope "voice.join". Выпускает LiveKit-токен для подключения бота к голосовому/медиа
        каналу — тот же membership check/Redis/Kafka/LiveKit flow, что и для людей через
        ChannelsApi.StartChannelConnection.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LeaveVoiceChannel(self, request, context):
        """Требует scope "voice.join". Отключает бота от голосового/медиа канала.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendMessage(self, request, context):
        """Требует scope "messages.send". Отправляет текстовое сообщение в текстовый канал от имени бота.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMessage(self, request, context):
        """Требует scope "messages.manage". Редактирует ранее отправленное ботом сообщение.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMessage(self, request, context):
        """Требует scope "messages.manage". Удаляет ранее отправленное ботом сообщение.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddReaction(self, request, context):
        """Требует scope "messages.manage". Добавляет emoji-реакцию от лица бота.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveReaction(self, request, context):
        """Требует scope "messages.manage". Убирает emoji-реакцию бота.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChannelMessages(self, request, context):
        """Требует intent GuildMessages. Последние сообщения канала (аналог MessagesApi.GetChannelMessages
        для людей) - позволяет боту получить контекст (историю) канала, а не только реагировать на новые
        события из Gateway. Отсортированы от старых к новым; для пагинации назад передавайте id самого
        старого полученного сообщения в before_id.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMessage(self, request, context):
        """Требует intent GuildMessages. Детали одного сообщения по его id - полезно, когда известен только
        message_id (например из InvokeMessageComponentRequest), без похода за всей историей канала.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Typing(self, request, context):
        """Требует scope "messages.manage". Индикатор "бот печатает" в канале.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTyping(self, request, context):
        """Требует scope "messages.manage". Реактивный статус "что бот сейчас делает" (Thinking/Explored/
        Processing/Reviewed/Opened/ReSearch/Fetched) — Discord/Claude-style, для случаев когда простого
        on/off Typing недостаточно (например пока агент вызывает инструменты перед ответом). Держится у
        клиента до следующего SetTyping, до отправки ботом реального сообщения в этот канал (SendMessage
        его автоматически снимает) или до серверного safety-net таймаута — явного "снять статус" вызова
        нет, см. BotTypingCommand в MessageActor.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMyGroups(self, request, context):
        """Требует scope "groups.read". Список групп, в которых состоит бот — без этого бот не может
        узнать, куда вообще отправлять сообщения/подключаться к каналам.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGroup(self, request, context):
        """Требует scope "groups.read". Детали одной группы (категории и каналы), в которой бот состоит.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGroupCategories(self, request, context):
        """Требует scope "groups.read". Лёгкий срез GetGroup - только категории (без вложенных каналов).
        Для бота, которому нужен только список/порядок категорий, без полного дерева.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGroupChannels(self, request, context):
        """Требует scope "groups.read". Лёгкий срез GetGroup - плоский список каналов, доступных боту
        (с учётом ViewChannels), без per-канального списка "кто сейчас в голосовом канале" - если
        нужна только структура, а не live-присутствие, этот вызов дешевле GetGroup.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGroupUsers(self, request, context):
        """Требует scope "groups.read". Текущие участники группы (common.User, включая ботов с is_bot = true).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUser(self, request, context):
        """Требует intent Guilds. Профиль произвольного пользователя по его id - без ограничения общей
        группой (как GetUserByIdCommand у людей): полезно, когда у бота есть только голый id
        (author_id сообщения, упомянутый пользователь), а не полный common.User.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def KickUser(self, request, context):
        """Требует intent Guilds. Реальная авторизация - Permissions.KickMembers через managed-роль бота;
        GroupActor уже проверяет иерархию (нельзя кикнуть участника с ролью выше/равной своей, владельца
        кикнуть нельзя вовсе) - тот же путь, что и для людей, никакого спецкейса для ботов.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGroupRoles(self, request, context):
        """Требует scope "groups.read". Список ролей группы, отсортированный по позиции ('@everyone'
        всегда последняя) — как и для людей (GroupsApi.GetGroupRoles), доступен любому участнику
        группы, не только владельцу: список ролей публичен внутри сервера, как в Discord.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChannel(self, request, context):
        """Требует scope "groups.read". Детали одного канала по его id — полезно, когда известен только
        channel_id (например из события гейтвея), без похода за всей группой через GetGroup.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RespondToInteraction(self, request, context):
        """Требует scope "interactions.respond". Отвечает на конкретный interaction (slash-команда, клик
        по компоненту, сабмит модалки или autocomplete-запрос), полученный ботом через /hubs/bots —
        см. Vc.Backend.WebApi.Interactions.InteractionActor, который ждёт этот ответ.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendInteractionFollowup(self, request, context):
        """Требует scope "interactions.respond". Дополнительное сообщение уже ПОСЛЕ начального ответа
        (аналог Discord webhook followup) — валидно только в пределах followup-окна interaction'а.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateCategory(self, request, context):
        """Требует intent Guilds (та же категория "структура/членство группы", что и GetGroup/GetGroupRoles).
        Реальная авторизация - Permissions.ManageChannels через managed-роль бота в GroupActor, как у людей.
        Создание группы/сервера ботам намеренно недоступно - только категории/каналы внутри уже
        существующей группы, в которой бот состоит.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateChannel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCategory(self, request, context):
        """Требует intent Guilds. Детали одной категории по её id - без ManageChannels (структура группы
        видна любому участнику, как в Discord), аналог GetChannel для категорий.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateChannel(self, request, context):
        """Требует intent Guilds + Permissions.ManageChannels. Переименовывает канал/категорию; каждый
        ответ - актуальное состояние сущности (id + все поля), а не пустой Empty, чтобы боту не
        приходилось отдельным запросом перечитывать то, что он только что изменил.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCategory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteChannel(self, request, context):
        """Требует intent Guilds + Permissions.ManageChannels. Ответ включает id удалённой сущности - тот
        же принцип, что и DeleteMessage/DeleteRole: даже "удаление" возвращает, что именно было удалено.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCategory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateRole(self, request, context):
        """Требует intent Guilds. Реальная авторизация - Permissions.ManageRoles через managed-роль бота;
        GroupActor уже проверяет иерархию ролей (нельзя выдать/создать роль выше собственной managed-роли
        бота) - тот же путь, что и для людей, никакого спецкейса для ботов.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateRole(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteRole(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssignRole(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveRole(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BotsApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMe': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMe,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=common__pb2.Bot.SerializeToString,
            ),
            'SetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.SetStatus,
                    request_deserializer=bots__pb2.SetStatusRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'JoinVoiceChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinVoiceChannel,
                    request_deserializer=bots__pb2.JoinVoiceChannelRequest.FromString,
                    response_serializer=bots__pb2.JoinVoiceChannelResponse.SerializeToString,
            ),
            'LeaveVoiceChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.LeaveVoiceChannel,
                    request_deserializer=bots__pb2.LeaveVoiceChannelRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=bots__pb2.SendMessageRequest.FromString,
                    response_serializer=bots__pb2.MessageInfo.SerializeToString,
            ),
            'UpdateMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMessage,
                    request_deserializer=bots__pb2.UpdateMessageRequest.FromString,
                    response_serializer=bots__pb2.MessageInfo.SerializeToString,
            ),
            'DeleteMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMessage,
                    request_deserializer=bots__pb2.DeleteMessageRequest.FromString,
                    response_serializer=bots__pb2.DeleteMessageResponse.SerializeToString,
            ),
            'AddReaction': grpc.unary_unary_rpc_method_handler(
                    servicer.AddReaction,
                    request_deserializer=bots__pb2.ReactionRequest.FromString,
                    response_serializer=bots__pb2.MessageInfo.SerializeToString,
            ),
            'RemoveReaction': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveReaction,
                    request_deserializer=bots__pb2.ReactionRequest.FromString,
                    response_serializer=bots__pb2.MessageInfo.SerializeToString,
            ),
            'GetChannelMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChannelMessages,
                    request_deserializer=bots__pb2.GetChannelMessagesRequest.FromString,
                    response_serializer=bots__pb2.GetChannelMessagesResponse.SerializeToString,
            ),
            'GetMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMessage,
                    request_deserializer=bots__pb2.GetMessageRequest.FromString,
                    response_serializer=bots__pb2.MessageInfo.SerializeToString,
            ),
            'Typing': grpc.unary_unary_rpc_method_handler(
                    servicer.Typing,
                    request_deserializer=bots__pb2.TypingRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SetTyping': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTyping,
                    request_deserializer=bots__pb2.BotTypingRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetMyGroups': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMyGroups,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=bots__pb2.GetMyGroupsResponse.SerializeToString,
            ),
            'GetGroup': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGroup,
                    request_deserializer=bots__pb2.GetGroupRequest.FromString,
                    response_serializer=bots__pb2.BotGroupDetails.SerializeToString,
            ),
            'GetGroupCategories': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGroupCategories,
                    request_deserializer=bots__pb2.GetGroupRequest.FromString,
                    response_serializer=bots__pb2.GetGroupCategoriesResponse.SerializeToString,
            ),
            'GetGroupChannels': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGroupChannels,
                    request_deserializer=bots__pb2.GetGroupRequest.FromString,
                    response_serializer=bots__pb2.GetGroupChannelsResponse.SerializeToString,
            ),
            'GetGroupUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGroupUsers,
                    request_deserializer=bots__pb2.GetGroupUsersRequest.FromString,
                    response_serializer=bots__pb2.GetGroupUsersResponse.SerializeToString,
            ),
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=bots__pb2.GetUserRequest.FromString,
                    response_serializer=common__pb2.User.SerializeToString,
            ),
            'KickUser': grpc.unary_unary_rpc_method_handler(
                    servicer.KickUser,
                    request_deserializer=bots__pb2.KickUserRequest.FromString,
                    response_serializer=bots__pb2.KickUserResponse.SerializeToString,
            ),
            'GetGroupRoles': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGroupRoles,
                    request_deserializer=bots__pb2.GetGroupRolesRequest.FromString,
                    response_serializer=bots__pb2.GetGroupRolesResponse.SerializeToString,
            ),
            'GetChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChannel,
                    request_deserializer=bots__pb2.GetChannelRequest.FromString,
                    response_serializer=bots__pb2.BotChannelDetails.SerializeToString,
            ),
            'RespondToInteraction': grpc.unary_unary_rpc_method_handler(
                    servicer.RespondToInteraction,
                    request_deserializer=bots__pb2.RespondToInteractionRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SendInteractionFollowup': grpc.unary_unary_rpc_method_handler(
                    servicer.SendInteractionFollowup,
                    request_deserializer=bots__pb2.SendInteractionFollowupRequest.FromString,
                    response_serializer=bots__pb2.MessageInfo.SerializeToString,
            ),
            'CreateCategory': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCategory,
                    request_deserializer=bots__pb2.CreateCategoryRequest.FromString,
                    response_serializer=bots__pb2.BotCategoryInfo.SerializeToString,
            ),
            'CreateChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateChannel,
                    request_deserializer=bots__pb2.CreateChannelRequest.FromString,
                    response_serializer=bots__pb2.BotChannelInfo.SerializeToString,
            ),
            'GetCategory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCategory,
                    request_deserializer=bots__pb2.GetCategoryRequest.FromString,
                    response_serializer=bots__pb2.BotCategoryInfo.SerializeToString,
            ),
            'UpdateChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateChannel,
                    request_deserializer=bots__pb2.UpdateChannelRequest.FromString,
                    response_serializer=bots__pb2.BotChannelInfo.SerializeToString,
            ),
            'UpdateCategory': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCategory,
                    request_deserializer=bots__pb2.UpdateCategoryRequest.FromString,
                    response_serializer=bots__pb2.BotCategoryInfo.SerializeToString,
            ),
            'DeleteChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteChannel,
                    request_deserializer=bots__pb2.DeleteChannelRequest.FromString,
                    response_serializer=bots__pb2.DeleteChannelResponse.SerializeToString,
            ),
            'DeleteCategory': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCategory,
                    request_deserializer=bots__pb2.DeleteCategoryRequest.FromString,
                    response_serializer=bots__pb2.DeleteCategoryResponse.SerializeToString,
            ),
            'CreateRole': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateRole,
                    request_deserializer=bots__pb2.CreateRoleRequest.FromString,
                    response_serializer=bots__pb2.BotRole.SerializeToString,
            ),
            'UpdateRole': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateRole,
                    request_deserializer=bots__pb2.UpdateRoleRequest.FromString,
                    response_serializer=bots__pb2.BotRole.SerializeToString,
            ),
            'DeleteRole': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteRole,
                    request_deserializer=bots__pb2.DeleteRoleRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'AssignRole': grpc.unary_unary_rpc_method_handler(
                    servicer.AssignRole,
                    request_deserializer=bots__pb2.RoleAssignmentRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'RemoveRole': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveRole,
                    request_deserializer=bots__pb2.RoleAssignmentRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bots.BotsApi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('bots.BotsApi', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BotsApi:
    """Self-service API: вызывается самим ботом по bot-токену (см. BotToken auth scheme в
    Vc.Backend.WebApi.Bots/Authentication), а не его владельцем. Для владельческого управления
    ботами (Keycloak JWT) см. user_bots.proto / UsersBots. Каждый метод (кроме GetMe) требует
    соответствующий scope — см. Vc.Common.Helpers.BotScopes и common.Bot.scopes.
    """

    @staticmethod
    def GetMe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bots.BotsApi/GetMe',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            common__pb2.Bot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bots.BotsApi/SetStatus',
            bots__pb2.SetStatusRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def JoinVoiceChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bots.BotsApi/JoinVoiceChannel',
            bots__pb2.JoinVoiceChannelRequest.SerializeToString,
            bots__pb2.JoinVoiceChannelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LeaveVoiceChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bots.BotsApi/LeaveVoiceChannel',
            bots__pb2.LeaveVoiceChannelRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bots.BotsApi/SendMessage',
            bots__pb2.SendMessageRequest.SerializeToString,
            bots__pb2.MessageInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bots.BotsApi/UpdateMessage',
            bots__pb2.UpdateMessageRequest.SerializeToString,
            bots__pb2.MessageInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bots.BotsApi/DeleteMessage',
            bots__pb2.DeleteMessageRequest.SerializeToString,
            bots__pb2.DeleteMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddReaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bots.BotsApi/AddReaction',
            bots__pb2.ReactionRequest.SerializeToString,
            bots__pb2.MessageInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveReaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bots.BotsApi/RemoveReaction',
            bots__pb2.ReactionRequest.SerializeToString,
            bots__pb2.MessageInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChannelMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bots.BotsApi/GetChannelMessages',
            bots__pb2.GetChannelMessagesRequest.SerializeToString,
            bots__pb2.GetChannelMessagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bots.BotsApi/GetMessage',
            bots__pb2.GetMessageRequest.SerializeToString,
            bots__pb2.MessageInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Typing(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bots.BotsApi/Typing',
            bots__pb2.TypingRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetTyping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bots.BotsApi/SetTyping',
            bots__pb2.BotTypingRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMyGroups(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bots.BotsApi/GetMyGroups',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            bots__pb2.GetMyGroupsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGroup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bots.BotsApi/GetGroup',
            bots__pb2.GetGroupRequest.SerializeToString,
            bots__pb2.BotGroupDetails.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGroupCategories(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bots.BotsApi/GetGroupCategories',
            bots__pb2.GetGroupRequest.SerializeToString,
            bots__pb2.GetGroupCategoriesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGroupChannels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bots.BotsApi/GetGroupChannels',
            bots__pb2.GetGroupRequest.SerializeToString,
            bots__pb2.GetGroupChannelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGroupUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bots.BotsApi/GetGroupUsers',
            bots__pb2.GetGroupUsersRequest.SerializeToString,
            bots__pb2.GetGroupUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bots.BotsApi/GetUser',
            bots__pb2.GetUserRequest.SerializeToString,
            common__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def KickUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bots.BotsApi/KickUser',
            bots__pb2.KickUserRequest.SerializeToString,
            bots__pb2.KickUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGroupRoles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bots.BotsApi/GetGroupRoles',
            bots__pb2.GetGroupRolesRequest.SerializeToString,
            bots__pb2.GetGroupRolesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bots.BotsApi/GetChannel',
            bots__pb2.GetChannelRequest.SerializeToString,
            bots__pb2.BotChannelDetails.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RespondToInteraction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bots.BotsApi/RespondToInteraction',
            bots__pb2.RespondToInteractionRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendInteractionFollowup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bots.BotsApi/SendInteractionFollowup',
            bots__pb2.SendInteractionFollowupRequest.SerializeToString,
            bots__pb2.MessageInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateCategory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bots.BotsApi/CreateCategory',
            bots__pb2.CreateCategoryRequest.SerializeToString,
            bots__pb2.BotCategoryInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bots.BotsApi/CreateChannel',
            bots__pb2.CreateChannelRequest.SerializeToString,
            bots__pb2.BotChannelInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCategory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bots.BotsApi/GetCategory',
            bots__pb2.GetCategoryRequest.SerializeToString,
            bots__pb2.BotCategoryInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bots.BotsApi/UpdateChannel',
            bots__pb2.UpdateChannelRequest.SerializeToString,
            bots__pb2.BotChannelInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateCategory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bots.BotsApi/UpdateCategory',
            bots__pb2.UpdateCategoryRequest.SerializeToString,
            bots__pb2.BotCategoryInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bots.BotsApi/DeleteChannel',
            bots__pb2.DeleteChannelRequest.SerializeToString,
            bots__pb2.DeleteChannelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCategory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bots.BotsApi/DeleteCategory',
            bots__pb2.DeleteCategoryRequest.SerializeToString,
            bots__pb2.DeleteCategoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateRole(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bots.BotsApi/CreateRole',
            bots__pb2.CreateRoleRequest.SerializeToString,
            bots__pb2.BotRole.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateRole(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bots.BotsApi/UpdateRole',
            bots__pb2.UpdateRoleRequest.SerializeToString,
            bots__pb2.BotRole.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteRole(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bots.BotsApi/DeleteRole',
            bots__pb2.DeleteRoleRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AssignRole(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bots.BotsApi/AssignRole',
            bots__pb2.RoleAssignmentRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveRole(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/bots.BotsApi/RemoveRole',
            bots__pb2.RoleAssignmentRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
