# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from voice.client._generated import interactions_pb2 as interactions__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in interactions_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InteractionsApiStub:
    """Discord-style Interactions API: владелец регистрирует slash-команды бота (CRUD), участники группы
    исполняют их / кликают компоненты бота / отправляют модалки - каждый такой вызов создаёт короткоживущий
    interaction, доставляется боту через /hubs/bots (Vc.Backend.WebApi.Bots.Consumer) и ждёт ответа
    (см. Actors/InteractionActor.cs).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterCommand = channel.unary_unary(
                '/interactions.InteractionsApi/RegisterCommand',
                request_serializer=interactions__pb2.RegisterCommandRequest.SerializeToString,
                response_deserializer=interactions__pb2.BotCommand.FromString,
                _registered_method=True)
        self.UpdateCommand = channel.unary_unary(
                '/interactions.InteractionsApi/UpdateCommand',
                request_serializer=interactions__pb2.UpdateCommandRequest.SerializeToString,
                response_deserializer=interactions__pb2.BotCommand.FromString,
                _registered_method=True)
        self.DeleteCommand = channel.unary_unary(
                '/interactions.InteractionsApi/DeleteCommand',
                request_serializer=interactions__pb2.DeleteCommandRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetBotCommands = channel.unary_unary(
                '/interactions.InteractionsApi/GetBotCommands',
                request_serializer=interactions__pb2.GetBotCommandsRequest.SerializeToString,
                response_deserializer=interactions__pb2.GetBotCommandsResponse.FromString,
                _registered_method=True)
        self.GetGroupCommands = channel.unary_unary(
                '/interactions.InteractionsApi/GetGroupCommands',
                request_serializer=interactions__pb2.GetGroupCommandsRequest.SerializeToString,
                response_deserializer=interactions__pb2.GetBotCommandsResponse.FromString,
                _registered_method=True)
        self.ExecuteCommand = channel.unary_unary(
                '/interactions.InteractionsApi/ExecuteCommand',
                request_serializer=interactions__pb2.ExecuteCommandRequest.SerializeToString,
                response_deserializer=interactions__pb2.InteractionResult.FromString,
                _registered_method=True)
        self.RequestAutocomplete = channel.unary_unary(
                '/interactions.InteractionsApi/RequestAutocomplete',
                request_serializer=interactions__pb2.RequestAutocompleteRequest.SerializeToString,
                response_deserializer=interactions__pb2.AutocompleteResult.FromString,
                _registered_method=True)
        self.InvokeMessageComponent = channel.unary_unary(
                '/interactions.InteractionsApi/InvokeMessageComponent',
                request_serializer=interactions__pb2.InvokeMessageComponentRequest.SerializeToString,
                response_deserializer=interactions__pb2.InteractionResult.FromString,
                _registered_method=True)
        self.SubmitModal = channel.unary_unary(
                '/interactions.InteractionsApi/SubmitModal',
                request_serializer=interactions__pb2.SubmitModalRequest.SerializeToString,
                response_deserializer=interactions__pb2.InteractionResult.FromString,
                _registered_method=True)


class InteractionsApiServicer:
    """Discord-style Interactions API: владелец регистрирует slash-команды бота (CRUD), участники группы
    исполняют их / кликают компоненты бота / отправляют модалки - каждый такой вызов создаёт короткоживущий
    interaction, доставляется боту через /hubs/bots (Vc.Backend.WebApi.Bots.Consumer) и ждёт ответа
    (см. Actors/InteractionActor.cs).
    """

    def RegisterCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBotCommands(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGroupCommands(self, request, context):
        """Commands from every bot member of the group in one call, instead of listing group members and
        calling GetBotCommands per bot. Any group member can call this (membership check happens in
        Groups, same as ExecuteCommand/etc. below) - BotCommand.bot_id disambiguates per-bot.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestAutocomplete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InvokeMessageComponent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitModal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InteractionsApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterCommand,
                    request_deserializer=interactions__pb2.RegisterCommandRequest.FromString,
                    response_serializer=interactions__pb2.BotCommand.SerializeToString,
            ),
            'UpdateCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCommand,
                    request_deserializer=interactions__pb2.UpdateCommandRequest.FromString,
                    response_serializer=interactions__pb2.BotCommand.SerializeToString,
            ),
            'DeleteCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCommand,
                    request_deserializer=interactions__pb2.DeleteCommandRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetBotCommands': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBotCommands,
                    request_deserializer=interactions__pb2.GetBotCommandsRequest.FromString,
                    response_serializer=interactions__pb2.GetBotCommandsResponse.SerializeToString,
            ),
            'GetGroupCommands': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGroupCommands,
                    request_deserializer=interactions__pb2.GetGroupCommandsRequest.FromString,
                    response_serializer=interactions__pb2.GetBotCommandsResponse.SerializeToString,
            ),
            'ExecuteCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteCommand,
                    request_deserializer=interactions__pb2.ExecuteCommandRequest.FromString,
                    response_serializer=interactions__pb2.InteractionResult.SerializeToString,
            ),
            'RequestAutocomplete': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestAutocomplete,
                    request_deserializer=interactions__pb2.RequestAutocompleteRequest.FromString,
                    response_serializer=interactions__pb2.AutocompleteResult.SerializeToString,
            ),
            'InvokeMessageComponent': grpc.unary_unary_rpc_method_handler(
                    servicer.InvokeMessageComponent,
                    request_deserializer=interactions__pb2.InvokeMessageComponentRequest.FromString,
                    response_serializer=interactions__pb2.InteractionResult.SerializeToString,
            ),
            'SubmitModal': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitModal,
                    request_deserializer=interactions__pb2.SubmitModalRequest.FromString,
                    response_serializer=interactions__pb2.InteractionResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'interactions.InteractionsApi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('interactions.InteractionsApi', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InteractionsApi:
    """Discord-style Interactions API: владелец регистрирует slash-команды бота (CRUD), участники группы
    исполняют их / кликают компоненты бота / отправляют модалки - каждый такой вызов создаёт короткоживущий
    interaction, доставляется боту через /hubs/bots (Vc.Backend.WebApi.Bots.Consumer) и ждёт ответа
    (см. Actors/InteractionActor.cs).
    """

    @staticmethod
    def RegisterCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/interactions.InteractionsApi/RegisterCommand',
            interactions__pb2.RegisterCommandRequest.SerializeToString,
            interactions__pb2.BotCommand.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/interactions.InteractionsApi/UpdateCommand',
            interactions__pb2.UpdateCommandRequest.SerializeToString,
            interactions__pb2.BotCommand.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/interactions.InteractionsApi/DeleteCommand',
            interactions__pb2.DeleteCommandRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBotCommands(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/interactions.InteractionsApi/GetBotCommands',
            interactions__pb2.GetBotCommandsRequest.SerializeToString,
            interactions__pb2.GetBotCommandsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGroupCommands(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/interactions.InteractionsApi/GetGroupCommands',
            interactions__pb2.GetGroupCommandsRequest.SerializeToString,
            interactions__pb2.GetBotCommandsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/interactions.InteractionsApi/ExecuteCommand',
            interactions__pb2.ExecuteCommandRequest.SerializeToString,
            interactions__pb2.InteractionResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestAutocomplete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/interactions.InteractionsApi/RequestAutocomplete',
            interactions__pb2.RequestAutocompleteRequest.SerializeToString,
            interactions__pb2.AutocompleteResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InvokeMessageComponent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/interactions.InteractionsApi/InvokeMessageComponent',
            interactions__pb2.InvokeMessageComponentRequest.SerializeToString,
            interactions__pb2.InteractionResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitModal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/interactions.InteractionsApi/SubmitModal',
            interactions__pb2.SubmitModalRequest.SerializeToString,
            interactions__pb2.InteractionResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
